FROM node:22-alpine AS build

ARG VITE_GIT_COMMIT=unknown
ARG VITE_BUILD_TIME=
ARG VITE_APP_ENV=prod

ENV VITE_GIT_COMMIT=$VITE_GIT_COMMIT \
    VITE_BUILD_TIME=$VITE_BUILD_TIME \
    VITE_APP_ENV=$VITE_APP_ENV

WORKDIR /app
COPY package.json ./
RUN npm install
COPY . .
RUN npm run build

FROM nginx:1.27-alpine
COPY nginx.prod.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/dist /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
